### ISSUE TITLE
Support GeoJSON literals in GeoSPARQL

### ISSUE THREAD

**Issue by dr-shorthair** [opengeospatial/ogc-geosparql#1]
New datatype `rdf:JSON` is introduced in [JSON-LD Syntax](https://w3c.github.io/json-ld-syntax/#the-rdf-json-datatype)

See https://github.com/w3c/json-ld-syntax/issues/353

**Comment by jabhay** [comment]
MoSCoW poll created

[![](https://api.gh-polls.com/poll/01EJXBPCEDYBJ7EWE3X67Q17YT/Must)](https://api.gh-polls.com/poll/01EJXBPCEDYBJ7EWE3X67Q17YT/Must/vote)
[![](https://api.gh-polls.com/poll/01EJXBPCEDYBJ7EWE3X67Q17YT/Should)](https://api.gh-polls.com/poll/01EJXBPCEDYBJ7EWE3X67Q17YT/Should/vote)
[![](https://api.gh-polls.com/poll/01EJXBPCEDYBJ7EWE3X67Q17YT/Could)](https://api.gh-polls.com/poll/01EJXBPCEDYBJ7EWE3X67Q17YT/Could/vote)
[![](https://api.gh-polls.com/poll/01EJXBPCEDYBJ7EWE3X67Q17YT/Won%27t)](https://api.gh-polls.com/poll/01EJXBPCEDYBJ7EWE3X67Q17YT/Won%27t/vote)

**Comment by dr-shorthair** [comment]
Discussion of this topic has moved to #48

**Comment by dr-shorthair** [comment]
Whoops - #48 is matching PR.

**Comment by mathib** [comment]
Is anyone aware of the apparent overlap with [this](https://www.ogc.org/standards/eo-geojson) OGC GeoJSON(-LD) extension specification? 

They mention GeoSPARQL with WKT literals as an alternative for GeoJSON-LD, since at the time of writing, the JSON-LD 1.0 spec did not support lists of lists (the current 1.1 version does btw).

In the revision of GeoSPARQL, we now defined an alternative approach based on GeoJSON literal, so there's no actual overlap with the above OGC standard, but there might be room for (initial) confusion. I think we should at least mention this OGC spec in the revisioned GeoSPARQL spec? Maybe the contributors to the OGC GeoJSON(-LD) extension specification can also provide input for our GeoSPARQL revision?

**Comment by situx** [comment]
I was not aware that there was a specification, but I was aware of [this](https://geojson.org/geojson-ld/) draft of it. In case we would have liked to refer to a GeoJSON class hierarchy similar to GML or Simple Features this is the vocabulary to use.

Maybe we should set up a meeting with the GeoJSON-LD people?

**Comment by VladimirAlexiev** [comment]
For the record, GeoSPARQL 1.1 allows geojson serialization:
- but it's expressed in a literal with datatype [geo:geoJSONLiteral](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_rdfs_datatype_geogeojsonliteral)
- not as "list of lists" as in https://geojson.org/geojson-ld/
