### ISSUE TITLE
Make underlying definitions available on the semantic web

### ISSUE THREAD

**Issue by lvdbrink** [opengeospatial/ogc-geosparql#10]
**Official change request**: [OGC CR 600](http://ogc.standardstracker.org/show_request.cgi?id=600)

GeoSPARQL is currently lacking in semantics that are available on the semantic web. For example, the concept of Geometry is not explained in GeoSPARQL itself, but has in its text definition a pointer to ISO 19107: "This class is equivalent to the UML class GM_Object defined in ISO 19107". Should one look up that document on the web, a paywall from ISO is hit. Such fundamental definitions should be directly accessible to consumers, both human and machine, on the semantic web, either as part of GeoSPARQL or as another web vocabulary.

**Comment by jabhay** [comment]
MoSCoW poll created

[![](https://api.gh-polls.com/poll/01EJXB8A9VVT4N9XGDBH9JYYQ1/Must)](https://api.gh-polls.com/poll/01EJXB8A9VVT4N9XGDBH9JYYQ1/Must/vote)
[![](https://api.gh-polls.com/poll/01EJXB8A9VVT4N9XGDBH9JYYQ1/Should)](https://api.gh-polls.com/poll/01EJXB8A9VVT4N9XGDBH9JYYQ1/Should/vote)
[![](https://api.gh-polls.com/poll/01EJXB8A9VVT4N9XGDBH9JYYQ1/Could)](https://api.gh-polls.com/poll/01EJXB8A9VVT4N9XGDBH9JYYQ1/Could/vote)
[![](https://api.gh-polls.com/poll/01EJXB8A9VVT4N9XGDBH9JYYQ1/Won%27t)](https://api.gh-polls.com/poll/01EJXB8A9VVT4N9XGDBH9JYYQ1/Won%27t/vote)

**Comment by jabhay** [comment]
@ghobona : It would make sense to me that the underlying infrastructure to accomplish this is already available in the OGC Naming Authority. Would you agree?

If so, my understanding is that we'd elect SWG representatives to the OGC Naming Authority, and then submit a PR into your already existing processes and viola, yes?

**Comment by FransKnibbe** [comment]
The GeoSPARQL function definitions found in the OGC definition server seem to be derived from the GeoSPARQL functions ontology (http://defs-dev.opengis.net/static/definitions/conceptschemes/functions_geosparql.ttl). The same has happened with the GeoSPARQL rule definitions. So if we want to add definitions to the OGC definition server the proper way to that would be to update the ontology code (geo.ttl is already here in GitHub, the files for the rules and functions should be added too) and then make sure that updates of the OGC definition server are part of the process of rolling out new versions of GeoSPARQL. Preferably fully automated.

As for the definitions of the basic GeoSPARQL classes (e.g. Geometry), I think they should be added to the main ontology file (geo.ttl).

**Comment by ghobona** [comment]
@lvdbrink please remember that there is a [GeoSPARQL ontology](http://schemas.opengis.net/geosparql/1.0/geosparql_vocab_all.rdf) on schemas.opengis.net. The GeoSPARQL ontology contains a "Geometry" class.

@jabhay We are currently looking into enabling the Definitions Server to support the publication of ontologies under the `/ont` tree. It's an infrastructural change so will take sometime to complete.

Regarding SWG representatives on the OGC-NA, yes, the SWG needs to elect a member to represent it on the OGC-NA.

**Comment by FransKnibbe** [comment]
This is a proposal for improved definitions of terms in the GeoSPARQL ontology. Its goals are:
1. To make definitions more universally understandable (not only for people in the geo-IT domain).
2.  To resolve references to information that is not freely accessible (i.e. ISO standards). 

### notes
* Listed are the existing (1.0) definition and a proposed definition for the next version (1.1).
* This message will be upated when required.
* I have adopted the guideline to use the skos:prefLabel in definitions  (hence the capitalisation of terms like Feature and Geometry).

# Classes

## SpatialObject
1.0: **The class spatial-object represents everything that can have a spatial representation. It is superclass of feature and geometry.**

1.1: **Anything spatial (having or being a shape, size or position). It is the superclass of Feature, Geometry and SpatialMeasure. The latter classes are expected to be used for instance data.**

### notes
* The definition is different from [the definition of Spatial Thing in Spatial Data on the Web Best Practices](https://www.w3.org/TR/sdw-bp/#glossary).
* The 1.0 definition seems too self-referential: X is anything that can be codified as X.
* I think definitions do not need to include class relationships, but in this case I think it makes sense, to indicate it is an abstract class.

## Feature
**1.0: This class represents the top-level feature type. This class is equivalent to GFI_Feature defined in ISO 19156:2011, and it is superclass of all feature types.**

**1.1: A spatial phenomenon in a universe of discourse. A Feature can be discrete (having a well-defined boundary or extent, for example an apple or a river) or can be continuous (for example: temperature, elevation).**

### notes
* The statement that is class is the superclass of all feature types is not clear, because the concept 'feature type' is not defined.
* The common definition is "Abstraction of real world phenomena". This leads to the questions:.
1. What is the _real world_? That is not easy to demarcate. The term is replaced with _universe of discourse_, but that change could be regarded as a broader concept and therefore problematic. 
2. Is it necessary to state that a Feature is an abstraction? Aren't all RDF classes abstractions?

## Geometry
1.0: The class represents the top-level geometry type. This class is equivalent to the UML class GM_Object defined in ISO 19107, and it is superclass of all geometry types.

1.1: A coherent set of direct positions. A direct position holds the coordinates for a position within a coordinate reference system (CRS).

### notes
* The term 'geometry type' is not defined, so it is left out of the new definition.
* The proposed definition is based on GM_object, but more thought needs to be given to the strictness of the definition. The term coordinate reference system (CRS) is used in the definition of GM_Object. Elsewhere in GeoSPARQL we use the term spatial reference system (SRS). Is there a difference between Spatial Reference Systems and Coordinate Reference Systems? 
CRS is clearly a framework for encoding position by coordinates. SRS is often taken to be a synonym. But it is possible to indicate position or shape by other means than coordinates. For example by address or geohash. Are systems like postal addressing, geohash or what3words spatial reference systems? Can anything not using numeric coordinates (for instance a GDDS cell) be a Geometry? 

## SpatialMeasure
1.1 (currently): This class represents a measurement of some dimension of a feature's spatial presence.
1.1 (proposed): A measurement or estimate of one or more dimensions of a Feature's spatial presence. It can be used to convey an idea of the size of a Feature. 

### notes
* I think mentioning 'size' is important to understanding this concept.

# Object properties
_coming later_
# Data properties
_coming later_
# Datatypes
_coming later_

**Comment by nicholascar** [comment]
I suggest adding to the section [4. Terms and definitions](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_terms_and_definitions) in addition to changes to the class definitions

**Comment by FransKnibbe** [comment]
> I suggest adding to the section [4. Terms and definitions](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_terms_and_definitions) in addition to changes to the class definitions

Thanks @nicholascar. At the moment, section 4 points to section 3 (Normative references). In section 3, there are two sources for definitions of spatial concepts: [Geographic information — Simple feature access — Part 1: Common architecture](https://www.ogc.org/standards/sfa) (SFA) and [the GML 3.2.1 encoding standard](https://portal.ogc.org/files/?artifact_id=20509) (GML321). There we can find the following definitions:

### SFA
- **coordinate system**: set of mathematical rules for specifying how coordinates are to be assigned to each point
- **coordinate reference system**: coordinate system that is related to the real world by a datum
- the term 'spatial reference system' is used, but not really defined. But it says "A Spatial Reference System, also referred to as a coordinate system, is a geographic (latitude-longitude), a projected (X, Y), or a geocentric (X, Y, Z) coordinate system."

### GML321
- **coordinate system**: set of mathematical rules for specifying how coordinates are to be assigned to points
- **coordinate reference system**: coordinate system that is related to an object by a datum
- **datum**: parameter or set of parameters that define the position of the origin, the scale, and the orientation of a coordinate system
- the term 'spatial reference system' is used (e.g. in attribute srsName), but not defined.

To clarify GeoSPARQL, I think it would be a good idea to include definitions of the three terms defined in GML321.  Shall I copy them to section 4?

Next to that, we need to find a normative/authoritative source for a definition of _spatial reference system_. Or just define the thing ourselves.

This is in [Topic 2: Spatial referencing by coordinates](https://docs.opengeospatial.org/as/18-005r4/18-005r4.html):

> Spatial references fall into two categories:
> - those using coordinates;
> - those based on geographic identifiers.

And we know by now that the DGGS spec introduces a third category (referencing by identifiers with structured geometry). 

So we could add another definition to section 4:
**spatial reference system**:  a system for establishing spatial position. A spatial reference system can use geographic identifiers, coordinates (in which case it is a coordinate reference system) or identifiers with structured geometry (in which case it is a Discrete Global Grid System).

Note: choice of definitions will have effect on the newly added `inSRS` property!
