### ISSUE TITLE
Function to retrieve lat/lon

### ISSUE THREAD

**Issue by situx** [opengeospatial/ogc-geosparql#160]
I just stumbled upon this StackOverflow post from many years ago asking how to retrieve lat/long from a GeoSPARQL-encoded geometry.
https://stackoverflow.com/questions/22536467/how-to-retrieve-latitude-and-longitude-from-geosparqls-wktliteral
The solution seems rather cumbersome.
Now with GeoSPARQL 1.1 we could (mis-)use e.g. the maxX() and maxY() function to retrieve lat/long from a single point, but it really seems like a fundamental thing to do that is currently not well supported in GeoSPARQL.
Any opinions about this?

**Comment by FransKnibbe** [comment]
I think minX() and maxY() should be sufficient if there is a clear and easy way to find out what X and Y mean. So this again shows the need for a CRS ontology and CRS registry based on that CRS ontology.

**Comment by FransKnibbe** [comment]
Also, I think it make sense to allow defining geometries directly in RDF. At least for point locations it would make sense. See also [issue 42](https://github.com/opengeospatial/ogc-geosparql/issues/42).

**Comment by jabhay** [comment]
A "solution" exists in 1.1. Shifting this to proposed scope for 1.2.

**Comment by SimonBin** [comment]
> I think maxX() and maxY() should be sufficient

I disagree because of the rest of your sentence, it would be very convenient to have lat and lon accessors. This is not a "solution"

We have implemented this as an extension to Apache Jena as `geof:lat` and `lon` and can recommend such functions to be added: https://github.com/Scaseco/jenax/blob/jena-4.8.0/jenax-arq-parent/jenax-arq-plugins-parent/jenax-arq-plugins-bundle/src/main/java/org/aksw/jena_sparql_api/sparql/ext/geosparql/GeoSparqlExFunctions.java#L133

**Comment by situx** [comment]
We merged #526 recently which propose a solution for this issue by defining the geof:easting and geof:northing functions. So this can be closed
