### ISSUE TITLE
owl:sameAs vs owl:equivalentProperty

### ISSUE THREAD

**Issue by mathib** [opengeospatial/ogc-geosparql#174]
Just a small comment on the use of `owl:sameAs` in the geo.ttl graph. I believe `owl:equivalentProperty` is better suited there, since it considers a link between two properties.

**Comment by paulc-dstl** [comment]
SameAs should be used to assert an individual is the same individual as another (eg Person A and Person B are one and the same). And can also be used for classes (where a class is an individual of type Class). But in this case for these two properties, is this not 'equality' rather than 'equivalence', hence sameAs rather than equivalentProperty, as per the spec. Although that then does imply properties are treated as individuals, which is problematic...

**Comment by FransKnibbe** [comment]
This is about expressing equivalence of the properties `:defaultGeometry` and `:hasDefaultGeometry`, right?
We want to express that those two are different IRIs for exactly the same thing. Apart from the IRI there is no difference. 

As for `owl:sameAs`:  looking at https://www.w3.org/TR/owl-ref/#sameAs-def, it says that it is to be used to declare equality between individuals. It also says that (in OWL Full), classes can be seen as individuals (instances of `owl:Class`). Can't we likewise regard the GeoSPARQL properties as instances of `owl:ObjectProperty` (and therefore as individuals)?

As for `owl:equivalentProperty`: https://www.w3.org/TR/owl-ref/#equivalentProperty-def says:

> Property equivalence is not the same as property equality. Equivalent properties have the same "values" (i.e., the same property extension), but may have different intensional meaning (i.e., denote different concepts). Property equality should be expressed with the owl:sameAs construct. As this requires that properties are treated as individuals, such axioms are only allowed in OWL Full.

With this as the meaning of 'property extension' (well, I did not know what it meant): 

> The property extension is the set of instances that is associated with the property. Instances of properties are not single elements, but subject-object pairs of property statements. In relational database terms, property instances would be called "tuples" of a binary relation (the property).

I think in this case we want to opt for equality instead of equivalence.

**Comment by mathib** [comment]
requiring OWL Full is a heavy burden for reasoners.. Would it be an option to use `owl:equivalentProperty`? If you look to the results while activating reasoning with it, you get the results that you would practically expect, no?

```
# asserted triples
ex:building1 geo:defaultGeometry ex:building1_geomA .
ex:building2 geo:hasDefaultGeometry ex:building2_geomA .
# the above together with the geosparql ontology using owl:equivalentProperty results in the following inferences:
ex:building1 geo:hasDefaultGeometry ex:building1_geomA .
ex:building2 geo:defaultGeometry ex:building2_geomA .
```

I believe the authors of OWL want to illustrate a subtle difference between the conceptual propertyX and the "instance" of propertyX applied in the predicate position of a triple. Using `owl:equivalentProperty` between two properties, means that the two conceptuals are equivalent but it does not mean that the property "instances" of the two conceptuals are equivalent. But in practice, since the conceptuals are interchangeable, this also results in triples with them being added when doing OWL reasoning.

**Comment by dr-shorthair** [comment]
The property definitions are instances of `owl:ObjectProperty` so _that_ is not a problem. 
But I agree with @mathib that `owl:sameAs` is more demanding than required, and `owl:equivalentProperty` expresses the intention just fine.

**Comment by nicholascar** [comment]
I also think `owl:equivalentProperty` does a better job of carrying the message we want carried.

**Comment by FransKnibbe** [comment]
Aaaand it is changed!
