### ISSUE TITLE
units of geof:buffer?

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#259]
The function `geof:buffer` already exists in GeoSPARQL 1.0. Its signature and description: 

`geof:buffer (geom: ogc:geomLiteral, radius: xsd:double, units: xsd:anyURI): ogc:geomLiteral`

_This function returns a geometric object that represents all Points whose distance from geom1 is less than or equal to the radius measured in units. Calculations are in the spatial reference system of geom1._

I have some questions about this:

1. Why have an argument for units here? What is wrong with always using CRS units? Especially when the definition says calculations use the SRS. 
2. With no guidance on the URI that indicates the unit to use. how are GeoSPARQL implementations to know which unit to use?
3. Can the unit argument be dropped in a newer version, or at least be made optional?
4. Can the unit argument be replaced by a toggle between CRS units and meters?

**Comment by situx** [comment]
My take on it:
1. Maybe it is inconvenient to use the CRS unit for this. After all, the radius you give as input parameter may also be a query variable representing a value of sth. in a different unit than the CRS and maybe even sth. you cannot modify because it is stored e.g. as a xsd:double value somewhere else in the LOD graph. We also do not define any conversion functions to metric values in GeoSPARQL 1.1, so the only option to convey a measure is by also giving a URI for the measurement as a parameter. Another argument is that we cannot change it in GeoSPARQL 1.1 because this is a GeoSPARQL 1.0 function.
2. I think there is a note in the GeoSPARQL 1.0 spec that indicates the use of an OGC vocabulary for units. In practice either this one or the qudt vocabulary are implemented. Page 20 of the GeoSPARQL 1.0 standard states:
> Several non-topological query functions use a unit of measure URI. The OGC has
> defined some standard units of measure URIs under the
> http://www.opengis.net/def/uom/OGC/1.0/ namespace, for example
> <http://www.opengis.net/def/uom/OGC/1.0/metre>
3. I think we cannot drop the unit. We could only define a different, i.e. new function signature for it
4. I am not sure how such a toggle would look like in function notation unless we define more function signatures. Could you give an example?

**Comment by FransKnibbe** [comment]
> 2\. I think there is a note in the GeoSPARQL 1.0 spec that indicates the use of an OGC vocabulary for units. In practice either this one or the qudt vocabulary are implemented. Page 20 of the GeoSPARQL 1.0 standard states:
> 
> > Several non-topological query functions use a unit of measure URI. The OGC has
> > defined some standard units of measure URIs under the
> > http://www.opengis.net/def/uom/OGC/1.0/ namespace, for example
> > http://www.opengis.net/def/uom/OGC/1.0/metre

Having a single UOM ontology would be a solution for getting a grip on the unit. to be used in the function. To be able to use anything in the wide open world would be asking too much from implementers, I think. Any URI from the OGC UOM definitions seems a much better prescription. But it would be good to have a link back to the section on UOM from any description of functions that use arbitrary units. 

The GeoSPARQL 1.1 text has changed though. It no longer mentions http://www.opengis.net/def/uom/OGC/1.0/, but refers to the OGC definition server. I tried a bit, but I can't find a fixed list of units there.

**Comment by situx** [comment]
Yes, I know. The problem was I believe that the OGC uom vocabulary is either not maintained and/or not sufficient. Therefore we removed the indication.
Currently I would recommend the usage of qudt

**Comment by jabhay** [comment]
Remaining tasks in this issue.
- [ ] Make this property like hasSize hasMetricSize.
- [ ] Determine whether we want to recommend QUDT for unit and add to the document.

**Comment by jabhay** [comment]
Removing the requirement to have metricBuffer. This ticket has been closed based on the recommendation to use QUDT. Only properties have metric and non-metric equivalents. If we believe it's necessary, this can be done in 1.2.

**Comment by FransKnibbe** [comment]
See [issue 286](https://github.com/opengeospatial/ogc-geosparql/issues/286) for a metric equivalent of geof:buffer.

**Comment by situx** [comment]
The function metricBuffer has been merged for GeoSPARQL 1.1 and a recommendation for QUDT has been added to the specification. Therefore, this ticket can be closed.
