### ISSUE TITLE
What does the units argument do in geof:distance?

### ISSUE THREAD

**Issue by FransKnibbe** [opengeospatial/ogc-geosparql#273]
This is the current description of the function geof:distance:

> ```
> geof:distance (geom1: ogc:geomLiteral,
>                geom2: ogc:geomLiteral,
>                units: xsd:anyURI): xsd:double
> ```
> Returns the shortest distance between any two Points in the two geometric objects. Calculations are in spatial reference system of geom1.

It is unclear to me what the `units` argument is supposed to do. If the calculations use the CRS of `geom1`, then the units of that CRS will be used. So which effect is the third argument to have?

**Comment by dr-shorthair** [comment]
This is an 'old chestnut'. @FransKnibbe you are in principle correct of course, but _finding_ the units of measure in a CRS definition is sometimes non-trivial - particularly if that is an online resource, and often the vertical and horizontal units in a 3D system are not the same. 

So it is convenient, and probably expected, to have a way to indicate this 'locally'.

**Comment by FransKnibbe** [comment]
@dr-shorthair, I do hope we will have some progress in the area of standardising CRS definitions on the Web, to make things like looking up the units of a CRS a lot easier.

But honestly, I still don´t understand what the `units` argument of `geof:distance` does. Is it meant to specify input or output units? Is it intended to override CRS units? Or to make them known? How could a SPARQL engine understand the unit specification from an arbitrary URI? And how could geodetic distance be calculated without extra CRS knowledge, apart from the unit?

**Comment by situx** [comment]
Hi Frans,
I think the unit parameter has merit. 
Suppose you have two geometries in the same CRS system which is defined in meters.
Section 8.7.1 in the GeoSPARQL 1.0 standard states:
"Returns the shortest distance in units between any two Points in the two geometric objects as calculated in the spatial reference system of geom1."
So this would allow me to ask geof:distance to return the distance in miles instead of meters as defined in the CRS.

This is also how the function is implemented in triple stores. They implement a limited amount of unit conversion functions which are able to convert between units described by unit URIs usually defined in the qudt namespace.

**Comment by FransKnibbe** [comment]
> Section 8.7.1 in the GeoSPARQL 1.0 standard states:
> "Returns the shortest distance in units between any two Points in the two geometric objects as calculated in the spatial reference system of geom1."
> So this would allow me to ask geof:distance to return the distance in miles instead of meters as defined in the CRS.

Ah, so a bit of vital information has disappeared between 1.0 and 1.1. 
Yes, if the argument sets output units, then it is good to have. Especially in the case where CRS units are angular.

I will propose a PR to fix the documentation.
