### ISSUE TITLE
Correct XMLns for gml?

### ISSUE THREAD

**Issue by SimonBin** [opengeospatial/ogc-geosparql#330]
The GeoSPARQL standard references [OGC07-036](https://portal.ogc.org/files/?artifact_id=20509) here: https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/spec/11-Part-08.adoc#geography-markup-language-serializationgml

which defines `http://www.opengis.net/gml/3.2` as the XML namespace of GML in section 5.1

This example file from the repo:
https://github.com/opengeospatial/ogc-geosparql/blob/7ac42091a9fdf90cefe5f051f5c616fb5a1af21e/1.1/moreton-island.gml#L41-L42
(currently removed)

likewise uses this namespace.

In the sole example on
https://github.com/opengeospatial/ogc-geosparql/blob/dc9cb57d6c8bf90a116c993c0f06f3d4b99b57cb/1.1/spec/11-Part-08.adoc?plain=1#L442-L447
however, a different namespace (the RDF Ontology namespace `http://www.opengis.net/ont/gml`) is used.

This creates interoperability problems when consuming a GML file from WFS and trying to load it into a gmlLiteral, as the XML tags do not match any more. Is this a bug/bad example in the standard? Or are we supposed to massage GML with `sed` to alter the XML namespaces?

Currently, Apache Jena hardcodes the NS from the example:
https://github.com/apache/jena/blob/231624d00188f58da6c15fcf5f940f0448111d02/jena-geosparql/src/main/java/org/apache/jena/geosparql/implementation/parsers/gml/GMLReader.java#L67

and is thus unable to correctly parse a GML geometry from a regular GML document

This also touches upon #144

**Comment by situx** [comment]
Hi, @SimonBin thank you for your question.

In the GeoSPARQL standard, we only define literal types, so we only define the type geo:gmlLiteral type in your case.
The goal is for you to encode literals in any version of GML that is published.
The namespace http://www.opengis.net/ont/gml is used for the additional RDF vocabulary describing the GML type hierarchy. This vocabulary, similarly to the Simple Features Vocabulary we provide with the standard is intended to classify Geometry instances in RDF.
So I see no reason to not use the GML 3.2 namespace or a GML 2.0 namespace in a GML literal.
Another question is why this example, which is also present in GeoSPARQL 1.0, is using the RDF namespace. 
I believe it is not wrong, because it references a valid GM_Object, but from a practical point of view it seems misleading.
@mperry455 since you worked on the GeoSPARQL 1.0 standard, was there a particular reason for you to put the RDF namespace in the GML literal instead of a GML 3.2 namespace or a GML 2.0 namespace?

**Comment by SimonBin** [comment]
after looking into it a bit more closely, I actually have reason to believe it **is wrong**, because `gml:pos` is _not_ specified at all in http://www.opengis.net/ont/gml as far as I can see, but only in http://schemas.opengis.net/gml/3.2.1/geometryBasic0d1d.xsd (which is included by http://www.opengis.net/gml/3.2)

**Comment by Aklakan** [comment]
Touching standard XML namespaces in an attempt to somehow link from the XML world to the RDF one seems like a bad idea as it breaks all tooling relying on those namespaces.

Strictly speaking, if an XML document uses a different namespace for GML then its no longer GML. If I used `rdfs:label` and declared `PREFIX rdfs: <http://myweb.site>` then I wouldn't be using the RDFS vocabulary either.

It is the GML/XML spec that would have to explicitly allow for using `http://www.opengis.net/ont/gml` as an alternative namespace.

If I understand your last sentence correctly, you agree that all implementations (not just jena) should support the conventional GML namespaces - right?

**Comment by mperry455** [comment]
@situx Right. GML literals should use the namespace for their GML version.

**Comment by situx** [comment]
Great! Then we have a linked pull request now to fix this issue
