### ISSUE TITLE
Update references to ISO19107 in GeoSPARQL

### ISSUE THREAD

**Issue by jabhay** [opengeospatial/ogc-geosparql#357]
We have references to ISO 19107 appears to have deprecated GM_Object. We'd like to ensure that as part of the update to GeoSPARQL we also update references to ISO 19107 reflect the current version as at the editing of GeoSPARQL 1.1.

Where necessary, we'll need to update explanatory text. e.g., https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_class_geogeometry. In https://github.com/opengeospatial/ogc-geosparql/pull/323, there is a good differentiation description.

**Comment by FransKnibbe** [comment]
I think there shouldn't be any references to ISO 19107 at all. It is not a particularly open standard. See also [issue 199](https://github.com/opengeospatial/ogc-geosparql/issues/199).

**Comment by dr-shorthair** [comment]
ISO standards are open.
They are not free.
These are separate concerns.

**Comment by ogcscotts** [comment]
if the reference to 19107 is normative for a requirement, then we can restate the content from 19107 (describe the dependency in the context of GeoSPARQL) or @ogcscotts can request permission to directly quote what is necessary from 19107.

**Comment by FransKnibbe** [comment]
Restating the content from 19107 is what has been attempted for GeoSPARQL 1.1. But having access to what is necesssary from 19107 is useful anyway. It will probably not be limited to a single definition though, because definitions typically use terms that also have definitions.

**Comment by dr-shorthair** [comment]
I agree @FransKnibbe that the situation with ISO standards is awkward. 

Probably there are two underlying issues at ISO:
(i) their business model relies on sales revenue to maintain the organization - perhaps a different funding model could be imagined? 
(iii) arguably CS standards have no business being managed in ISO, since the community expectation is that they are freely available. This is in contrast with industry standards around things like plumbing and physical engineering practice, where buying these standards would be a natural cost of doing business in sectors where standards certification is part of doing business and revenue streams are tuned to that. 

ISO standards are Open in the sense that there is no restriction on who can use them, no in-club and out-club. 

I do get frustrated when people based in universities complain about access to standards and compare it unfavourably to journal papers ... which their institution is typically paying a subscription to. Journals are equally inaccessible to people not affiliated with institutions, but somehow academics don't see it that way (and don't lobby their libraries to have a subscription to ISO).

**Comment by nicholascar** [comment]
@ogcscotts: the reference to ISO19107 is not normative but comparative. GeoSPARQL defines its `Geometry` class on its own terms _with comparative reference to_ ISO19107. So we don't have to do much with 19107. I have quoted a small snippet of current 19107 in the comparison.

I've removed the only other 19107 reference in the doc since ref to GML 3.2.2 can be made instead since GML 3.2.2 is 19107-conformant.

So I think my PR #365 will close this issue.
