### ISSUE TITLE
Move GeoSPARQL documents over to ISO doc standard

### ISSUE THREAD

**Issue by jabhay** [opengeospatial/ogc-geosparql#426]
ISO has a standard template for ISO documentation with an OGC flavour. We will be maintaining our documents using that template going forward.

Acceptance Criteria
- [ ] Our documents have been moved over to the OGC flavour of the ISO documentation
- [ ] Our CI process is updated to build the documentation and is passing

**Comment by situx** [comment]
The current ISO version of GeoSPARQL can be found here: https://github.com/situx/mn-samples-ogc/actions
@nicholascar There is an issue in section A.4 since the same URIs have been used for more than one requirement (the DGGS ones) and the document does not compile with this settings. Would we need to rename these requirement URIs?

**Comment by situx** [comment]
@jabhay Questions for Scott:
I think all issues have been solved, I would just ask if the document apart from the issue in A.4 is acceptable and we would need to add the abstract.
