### ISSUE TITLE
Parsing error of version 1.1

### ISSUE THREAD

**Issue by gatemezing** [opengeospatial/ogc-geosparql#495]
Hello,
I am having an error when trying to parse the [v.11 of the ontology](https://opengeospatial.github.io/ogc-geosparql/geosparql11/geo.ttl). For example, using [this tool](http://rdf.greggkellogg.net/distiller?command=serialize&format=turtle&output_format=ntriples), it complains with this line `Statement #<RDF::Statement:0x78604(_:g492840 <https://schema.org/email> "matthew.perry@oracle.com"^^<http://www.w3.org/2001/XMLSchema#anyURI> .)> is invalid`

Am I the only one having this issue? I want to use the N3 version to be loaded into LOV for keeping track.

**Comment by situx** [comment]
Hi @gatemezing,

I checked this issue just now.
The email addresses of the contributors have been typed as xsd:anyURI which is technically not correct, since they do not represent URLs.
Changing them to xsd:string solves this issue and I will apply fixes to all versions of the files shortly.

We do have continuous integration scripts using rdflib which do not through an error here, so good to have your feedback that there are more strict parsers out there finding this issue.

**Comment by gatemezing** [comment]
HI @situx , thank you for the fix. I've tested the file and no error. Sorry for the delay.

**Comment by situx** [comment]
Sorry, I forgot to update one email address to xsd:string.
This is now done and I have generated n3 versions of the vocabularies on our Github page:
https://opengeospatial.github.io/ogc-geosparql/

**Comment by gatemezing** [comment]
Great, thank you.

**Comment by gatemezing** [comment]
Thank you @situx ! All good!
