### ISSUE TITLE
Support for 2D and 3D Cartesian coordinate systems?

### ISSUE THREAD

**Issue by ebremer** [opengeospatial/ogc-geosparql#557]
Is there support for 2D and 3D Cartesian coordinate systems in GeoSPARQL?

My use case is using GeoSPARQL to represent morphological features in Pathology Whole Slide Images such as nuclei, necrotic regions, tumor regions, etc.   ROIs are represented with WKT literals.  Being able to do spatial queries such as finding tumor infiltrating lymphocytes (TILs) that are within distance of X microns of a tumor region of particular area would be quite useful.

Additionally, support for "pixel" units when data is based on a 2D pixel or 3D voxel coordinate system.

**Comment by jabhay** [comment]
Hi @ebremer,

GeoSPARQL already supports EWKT which includes a CRS URI. EPSG has a number of 2D and 3D cartesian coordinate systems defined, which should meet your requirements here, unless I'm misunderstanding them? Whilst this site isn't the authoritative IOGP one, it did give me a search that let me find such CRSs: https://epsg.io/?q=%20kind%3ACARTESCS. Assuming you can provide a URI for the pixel/voxel coordinate systems you want to use, you should be able to use ogc:wktLiteral for this purpose.

Let me know if I've missed something. Otherwise, feel free to close the ticket.

Jo

**Comment by ebremer** [comment]
@jabhay thanks for responding.  I've been digging into this more and you are correct, I have found the 2D/3D coordinate systems and tested them on a Virtuoso instance.  It looks like need a SRS that is not only Cartesian 2D/3D, but units that are in micrometers.  From the list you sent me, they are all in meters.   I will try to create a custom SRS.
